[project]
name = "spatial-project-geo-dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "nsasamuel2563@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.6",
    "requests>=2.34.2",
]

[project.scripts]
spatial-project-geo-dev = "spatial_project_geo_dev:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
